# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/*
- main
- master
- develop

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  poolName: 'Test'
  artifaceName: aks
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build the web application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: $(poolName)
    
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'Walmart'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'Docker Hub Connection'
        tags: |
          $(tag)
          
    # - upload: aks
    #   artifact: aks
